In [1]:
import os
import csv
import pandas as pd

In [2]:
data_file = "../Top10_Conditions_by_Year.csv"

In [3]:
data_file_pd = pd.read_csv(data_file)
data_file_pd.head(2)

   Year             Condition  Count
0  2009  Hepatitis C, chronic    133
1  2009         Salmonellosis    119

In [9]:
pivoted_table = data_file_pd.pivot(index="Year", columns="Condition", values="Count")
pivoted_table.reset_index(inplace=True)
pivoted_table

Condition,Year,Campylobacteriosis,Cryptosporidiosis,"Escherichia coli infection, Shiga Toxin-Producing",Giardiasis,"Haemophilus influenzae, invasive","Hepatitis B, chronic","Hepatitis C, chronic","Lead, elevated levels",Legionellosis,Lyme disease,Pertussis,Salmonellosis,Spotted Fever Rickettsiosis (including RMSF),"Streptococcus, Group A, invasive",Varicella (Chickenpox)
0,2009,103.0,NaN,NaN,80.0,NaN,102.0,133.0,82.0,NaN,65.0,60.0,119.0,NaN,53.0,85.0
1,2010,110.0,NaN,NaN,73.0,NaN,111.0,132.0,78.0,NaN,80.0,71.0,120.0,NaN,64.0,84.0
2,2011,114.0,NaN,NaN,66.0,NaN,112.0,133.0,71.0,NaN,81.0,63.0,121.0,73.0,NaN,84.0
3,2012,114.0,NaN,NaN,70.0,NaN,98.0,132.0,64.0,NaN,87.0,87.0,112.0,92.0,NaN,81.0
4,2013,99.0,NaN,NaN,68.0,NaN,107.0,132.0,NaN,NaN,94.0,84.0,117.0,82.0,65.0,68.0
5,2014,109.0,NaN,NaN,66.0,NaN,109.0,134.0,NaN,NaN,94.0,77.0,122.0,89.0,73.0,74.0
6,2015,121.0,64.0,NaN,68.0,NaN,113.0,133.0,NaN,NaN,103.0,NaN,122.0,80.0,64.0,68.0
7,2016,122.0,NaN,NaN,65.0,63.0,106.0,133.0,101.0,NaN,85.0,NaN,121.0,79.0,80.0,NaN
8,2017,123.0,NaN,NaN,NaN,77.0,113.0,133.0,108.0,NaN,105.0,NaN,129.0,80.0,80.0,71.0
9,2018,122.0,NaN,78.0,76.0,NaN,115.0,132.0,109.0,73.0,90.0,NaN,122.0,81.0,NaN,NaN

In [10]:
pivoted_table.to_csv("Top10_Pivoted.csv", index=False)